name: Superpickaxe
version: 1.1
authors: 
 - DiddiZ 
 - Asacavanagh
main: de.diddiz.superpickaxe.Superpickaxe
description: Adds a simple super pickaxe.
softdepend: [LogBlock, WorldEdit]
commands:
  spa:
    description: 'Enables or disables super pickaxe'
    usage: 'Usage: /<command>'
    aliases: []
permissions:
    superpickaxe.use:
        description: 'Allows to use the super pickaxe'
        default: op
    superpickaxe.breakAll:
        description: 'Allows the user to break any blocks'
        default: op
    superpickaxe.notooldamage:
        description: 'Disables tool damage when using spa tools'
        default: op